### PR TITLE
Migrated to .NET Standard 2.0 and upgraded to RavenDB 4.2.2

### PR DESCRIPTION
**Pull request by plneto**
Hi, I needed to use this Sink for my new project which uses RavenDB 4.2.2 and it wasn't working with the current nuget package so I decided to re-write it using netstandard 2.0.

Let me know what you guys think or if you have any suggestions.

Thanks

Change log:
 - Migrated Serilog.Sinks.RavenDB to netstandard 2.0
 - Updated RavenDB.Client and RavenDB.Embeded to version 4.2.2
 - Use `Constants.Documents.Metadata.Expires` to set the expiry date in the metadata
 - Use a new Guid for each test's database so the data is not shared between tests

A few things to do before merging this PR:
-  revert the package id in the nuspec
-  replace the secure nuget api key in the appveyor.yml file as it's using mine.  (use https://ci.appveyor.com/tools/encrypt)

This is the temp nuget package if anyone wants to test it - https://www.nuget.org/packages/Serilog.Sinks.RavenDB.Temp/

### CODE REVIEW

**Comment by ThatOhio** [comment]
Thanks for doing this! I'm using your branch for now for the project I'm working on, but I'm wondering when/if these changes will make it to the actual sink, would prefer to simply include the nuget package as opposed to maintaining a copy of this for now.

**Comment by plneto** [comment]
I agree. It'd be great if the maintainer could merge this PR or give some feedback.

**Comment by nblumhardt** [comment]
Sorry about the long delay- this repo has had no maintainer for some time; we've just had an offer of help, see #8, hopefully everything will be rolling along again soon 😎

**Comment by viceroypenguin** [comment]
Superseded by #10 (with contribution acknowledgement)

**Pull request closed without merging**
